version: '3.9'

services:
  backend:
    build: .
    container_name: moviehub-back
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: moviehub-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Aa1234556
      MYSQL_DATABASE: moviehub
    ports:
      - "3306:3306"
    volumes:
      - moviehub-db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  moviehub-db-data:
